### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by neersighted** [paulirish/git-open#133]
Now that #132 has been landed, I'd appreciate a new release, so I don't need to install from git.

Thanks!

**Comment by derimagia** [comment]
@paulirish are you able to make a release?

**Comment by paulirish** [comment]
Can do. Been one year since 2.0.0

![image](https://user-images.githubusercontent.com/39191/49393625-a4a52f00-f6e6-11e8-875f-48bc1a918789.png)


Looks like most changes are bugfixes but the newly added support for Bitbucket with diff root context and CWS Code commit means we should go with 2.1.0

I'll prep that.
