### ISSUE TITLE
git open pr

### ISSUE THREAD

**Issue by msaspence** [paulirish/git-open#47]
It would be nice to be able to run `git open pr` and get the first PR it finds for the current branch.

**Comment by paulirish** [comment]
sure. sg.

**Comment by paulirish** [comment]
pr welcome. :)

**Comment by Bates550** [comment]
A friend and I gave this a go and it kind of works! https://github.com/Bates550/git-open/pull/1

It won't find PRs across forks however and it doesn't seem to work on private repos for what I'm guessing are authentication reasons.

**Comment by paulirish** [comment]
Made the PR for you over here: https://github.com/paulirish/git-open/pull/53

**Comment by hotoo** [comment]
See https://github.com/hotoo/gitopen

**Comment by msaspence** [comment]
and if one doesn't exist go to https://github.com/{project}/compare/{branch}?expand=1

**Comment by derimagia** [comment]
git-extras has 2 commands for `git-pr` and `git-mr`, Personally think those are a bit better to use because this gets a bit weird with a bunch of different git hosting providers. https://github.com/tj/git-extras

Personally I'm a bit against this for git-open since this will require work for every hosting provider and will be a decent amount of code for it. I think it's a job for another command. Also `git open pr` sounds like you're opening a pr...

**Comment by derimagia** [comment]
Going to close this as git-open doesn't make api requests like this, it is only for opening your browser ti specific parts of your git repo. 

Existing Alternatives:
1) https://github.com/github/hub (Github :octocat:)
2) https://github.com/guyzmo/git-repo (Has this plus a lot of provider-specific functionality for Github :octocat:, Bitbucket, Gitlab, Gogs) 
3) https://github.com/tj/git-extras (Has `git-pull-request` Github :octocat:)

**Comment by MartinDelille** [comment]
For Gitlab: https://github.com/zaquestion/lab
